<template>
  <div class="analysis-result">
    <div class="result-header">
      <h4 class="result-title">Analysis Result</h4>
      <span class="demo-badge" title="Results generated by rule-based demo analysis, not an LLM">Demo AI</span>
    </div>

    <div v-if="result.detectedRole" class="result-row">
      <span class="result-label">Detected Role</span>
      <span class="result-value">{{ result.detectedRole }}</span>
    </div>

    <div class="result-row">
      <span class="result-label">Technologies</span>
      <div v-if="result.technologies.length" class="badge-list">
        <span v-for="tech in result.technologies" :key="tech" class="badge">{{ tech }}</span>
      </div>
      <span v-else class="empty-inline">None detected</span>
    </div>

    <div class="result-row">
      <span class="result-label">Keywords</span>
      <div v-if="result.keywords.length" class="badge-list">
        <span v-for="kw in result.keywords" :key="kw" class="badge badge-neutral">{{ kw }}</span>
      </div>
      <span v-else class="empty-inline">None detected</span>
    </div>

    <div class="result-row">
      <span class="result-label">Matched Skills</span>
      <div v-if="result.matchedResumeSkills.length" class="badge-list">
        <span v-for="skill in result.matchedResumeSkills" :key="skill" class="badge badge-success">{{ skill }}</span>
      </div>
      <span v-else class="empty-inline">No resume skills matched</span>
    </div>

    <div class="result-row">
      <span class="result-label">Missing Skills</span>
      <div v-if="result.missingSkills.length" class="badge-list">
        <span v-for="skill in result.missingSkills" :key="skill" class="badge badge-missing">{{ skill }}</span>
      </div>
      <span v-else class="empty-inline">None — good coverage</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { JobAnalysisResponse } from '@/api/ai'

defineProps<{ result: JobAnalysisResponse }>()
</script>

<style scoped>
.analysis-result {
  display: flex;
  flex-direction: column;
  gap: 0.875rem;
}

.result-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.result-title {
  font-size: 0.9375rem;
  font-weight: 600;
  color: var(--color-text);
}

.demo-badge {
  font-size: 0.6875rem;
  font-weight: 500;
  padding: 0.15rem 0.5rem;
  border-radius: 999px;
  background: #f3f4f6;
  color: var(--color-text-muted);
  border: 1px solid var(--color-border);
  cursor: default;
}

.result-row {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
}

.result-label {
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--color-text-muted);
}

.result-value {
  font-size: 0.875rem;
  color: var(--color-text);
  font-weight: 500;
}

.badge-list {
  display: flex;
  flex-wrap: wrap;
  gap: 0.375rem;
}

.badge-success {
  background: #dcfce7;
  color: #166534;
}

.badge-missing {
  background: #fef2f2;
  color: #991b1b;
}

.empty-inline {
  font-size: 0.8125rem;
  color: var(--color-text-muted);
  font-style: italic;
}
</style>
