<template>
  <div class="tailoring-suggestions">
    <div class="suggestions-header">
      <h4 class="result-title">Tailoring Suggestions</h4>
      <span class="demo-badge" title="Suggestions generated by rule-based demo analysis, not an LLM">Demo AI</span>
    </div>

    <div v-if="suggestions.length === 0" class="empty-state">
      No tailoring suggestions were generated for this resume.
    </div>

    <template v-else>
      <ul class="suggestion-list">
        <li v-for="(s, i) in suggestions" :key="i" class="suggestion-item" :class="{ 'suggestion-item--accepted': accepted.has(i), 'suggestion-item--rejected': rejected.has(i) }">
          <div class="suggestion-block">
            <span class="block-label">Original</span>
            <p class="block-text original-text">{{ s.originalText }}</p>
          </div>

          <div class="suggestion-block">
            <span class="block-label">Tailored Suggestion</span>
            <p class="block-text suggested-text">{{ s.suggestedText }}</p>
          </div>

          <div v-if="s.matchedKeywords.length" class="suggestion-block">
            <span class="block-label">Matched Keywords</span>
            <div class="badge-list">
              <span v-for="kw in s.matchedKeywords" :key="kw" class="badge">{{ kw }}</span>
            </div>
          </div>

          <div class="suggestion-block">
            <span class="block-label">Rationale</span>
            <p class="rationale-text">{{ s.rationale }}</p>
          </div>

          <div class="suggestion-actions">
            <button
              class="btn btn-sm"
              :class="accepted.has(i) ? 'btn-primary' : 'btn-ghost'"
              :aria-pressed="accepted.has(i)"
              @click="toggle(i, 'accept')"
            >
              {{ accepted.has(i) ? '✓ Accepted' : 'Accept' }}
            </button>
            <button
              class="btn btn-sm"
              :class="rejected.has(i) ? 'btn-danger' : 'btn-ghost'"
              :aria-pressed="rejected.has(i)"
              @click="toggle(i, 'reject')"
            >
              {{ rejected.has(i) ? '✕ Rejected' : 'Reject' }}
            </button>
          </div>
        </li>
      </ul>

      <div class="apply-bar">
        <button
          class="btn btn-primary"
          :disabled="accepted.size === 0 || loading"
          data-testid="apply-btn"
          @click="apply"
        >
          <span v-if="loading" class="spinner" aria-hidden="true" />
          {{ loading ? 'Applying…' : `Apply ${accepted.size} Accepted Suggestion${accepted.size !== 1 ? 's' : ''}` }}
        </button>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { BulletSuggestion, AcceptedSuggestion } from '@/api/ai'

const props = defineProps<{ suggestions: BulletSuggestion[]; loading?: boolean }>()
const emit = defineEmits<{ apply: [accepted: AcceptedSuggestion[]] }>()

const accepted = ref(new Set<number>())
const rejected = ref(new Set<number>())

function toggle(i: number, action: 'accept' | 'reject') {
  const primary = action === 'accept' ? accepted : rejected
  const other = action === 'accept' ? rejected : accepted
  if (primary.value.has(i)) {
    primary.value.delete(i)
  } else {
    primary.value.add(i)
    other.value.delete(i)
  }
  // trigger reactivity
  accepted.value = new Set(accepted.value)
  rejected.value = new Set(rejected.value)
}

function apply() {
  const payload: AcceptedSuggestion[] = [...accepted.value].map((i) => ({
    experienceId: props.suggestions[i]!.experienceId,
    suggestedText: props.suggestions[i]!.suggestedText,
  }))
  emit('apply', payload)
}
</script>

<style scoped>
.tailoring-suggestions {
  display: flex;
  flex-direction: column;
  gap: 0.875rem;
}

.suggestions-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.result-title {
  font-size: 0.9375rem;
  font-weight: 600;
  color: var(--color-text);
}

.demo-badge {
  font-size: 0.6875rem;
  font-weight: 500;
  padding: 0.15rem 0.5rem;
  border-radius: 999px;
  background: #f3f4f6;
  color: var(--color-text-muted);
  border: 1px solid var(--color-border);
  cursor: default;
}

.suggestion-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.suggestion-item {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  padding: 1rem;
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  background: var(--color-surface);
}

.suggestion-block {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.block-label {
  font-size: 0.6875rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--color-text-muted);
}

.block-text {
  font-size: 0.875rem;
  line-height: 1.5;
  color: var(--color-text);
}

.original-text {
  color: var(--color-text-muted);
}

.suggested-text {
  color: var(--color-text);
  font-weight: 500;
}

.badge-list {
  display: flex;
  flex-wrap: wrap;
  gap: 0.375rem;
}

.suggestion-item--accepted {
  border-color: var(--color-primary);
  background: #f5f3ff;
}

.suggestion-item--rejected {
  opacity: 0.5;
}

.suggestion-actions {
  display: flex;
  gap: 0.5rem;
  margin-top: 0.25rem;
}

.btn-danger {
  background: #fee2e2;
  color: #b91c1c;
  border: 1px solid #fca5a5;
}

.apply-bar {
  display: flex;
  justify-content: flex-end;
  padding-top: 0.5rem;
}
</style>
